### ISSUE TITLE
Uncaught TypeError: Cannot read property 'substr' of undefined

### ISSUE THREAD

**Issue by MrEbbinghaus** [freshl/atom-compile-coffee#2]
Uncaught TypeError: Cannot read property 'substr' of undefined

**Atom Version**: 0.155.0
**System**: Mac OS X 10.10.1
**Thrown From**: [atom-compile-coffee](https://github.com/freshl/atom-compile-coffee) package, v1.3.0
### Steps To Reproduce
1. ...
2. ...
### Stack Trace

```
At /Users/bjebb/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:48

TypeError: Cannot read property 'substr' of undefined
  at atomCompileCoffee (/Users/bjebb/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:48:23)
  at atom-workspace.<anonymous> (/Users/bjebb/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:68:48)
  at atom-workspace.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:167:20)

```

/cc @atom/core

**Comment by GabLeRoux** [comment]
Happens to me too

### Steps to reproduce

1. Create a new file
2. Set as html
3. Write some html
4. Open Html Live Preview (`cmd+shift+p` `atom HTML preview: Toggle`)
5. Save (`cmd+s`)

I wasn't using atom-compile-coffee for this page (or should I enable it only when I need it?). HTML did not contain any javascript. I couldn't save any other file after having this issue.

**Atom Version**: 0.177.0
**System**: Mac OS X 10.10.2
**Thrown From**: [atom-compile-coffee](https://github.com/freshl/atom-compile-coffee) package, v1.3.0

### Stack Trace

Uncaught TypeError: Cannot read property 'substr' of undefined

```
At /Users/gableroux/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:48

TypeError: Cannot read property 'substr' of undefined
  at atomCompileCoffee (/Users/gableroux/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:48:23)
  at atom-workspace.<anonymous> (/Users/gableroux/.atom/packages/atom-compile-coffee/lib/atom-compile-coffee.coffee:68:48)
  at atom-workspace.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:170:20)

```

### Commands

```
     -0:04.2 core:paste (atom-text-editor.editor.is-focused)
     -0:03.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "timecop",
      "vim-mode",
      "symfony-snippets"
    ]
  }
}
```

### Installed Packages

```coffee
# User
ScssBundle, v0.4.0
angularjs, v0.1.0
ascii-codes, v0.3.3
atom-compile-coffee, v1.3.0
atom-django, v0.2.0
autocomplete-plus, v2.0.10
build, v0.23.3
coffee-lint, v0.7.3
coffee-refactor, v0.6.2
color-picker, v1.4.4
css-snippets, v0.5.0
editorconfig, v0.3.0
grunt-runner, v0.6.0
js-refactor, v0.3.0
language-blade, v0.7.0
language-erlang, v2.0.0
language-gitignore, v0.1.1
language-ini, v1.3.0
language-python-django-templates, v0.1.0
laravel, v0.4.2
laravel-facades, v1.0.0
linter, v0.11.1
linter-pylint, v0.2.0
linter-scss-lint, v0.0.11
linter-xmllint, v0.0.5
minimap, v4.0.2
minimap-git-diff, v3.1.1
refactor, v0.4.1
scope-inspector, v0.2.1
ssh-config, v0.10.0
travis-ci-status, v0.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by ramongr** [comment]
Same problem here

**Comment by r-murphy** [comment]
I encountered this as well. Easy to reproduce. 
1. Cmd+N (File>New File)
2. Cmd+S (File>Save)

The workaround is Shift+Cmd+S (File>Save as), although ideally Save should behave like Save As if it's a new file.
